dbt_riverflood:
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{env_var('AIRFLOW_VAR_GCP_PROJECT_ID')}}"
      dataset: "river_observation_dev"
      threads: 1 # Must be a value of 1 or greater
      # These fields come from the service account json keyfile
      keyfile_json:
        type: service_account
        project_id: " {{env_var('AIRFLOW_VAR_GCP_PROJECT_ID')}} "
        private_key_id: "28f0879bf787904cd54da8deb20c4e05623b6019"
        private_key: "{{env_var('GCP_JSON_PRIVATE_KEY')}}"
        client_email: airflow-connexion@riverflood-lewagon.iam.gserviceaccount.com
        client_id: "117984266685240404291"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/airflow-connexion%40riverflood-lewagon.iam.gserviceaccount.com"
    prod:
      type: bigquery
      method: service-account-json
      project: "{{env_var('AIRFLOW_VAR_GCP_PROJECT_ID')}}"
      dataset: "river_observation_prod"
      threads: 1 # Must be a value of 1 or greater
      # These fields come from the service account json keyfile
      keyfile_json:
        type: service_account
        project_id: " {{env_var('AIRFLOW_VAR_GCP_PROJECT_ID')}} "
        private_key_id: "28f0879bf787904cd54da8deb20c4e05623b6019"
        private_key: "{{env_var('GCP_JSON_PRIVATE_KEY')}}"
        client_email: airflow-connexion@riverflood-lewagon.iam.gserviceaccount.com
        client_id: "117984266685240404291"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/airflow-connexion%40riverflood-lewagon.iam.gserviceaccount.com"
  target: dev
