# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "riverflood-lewagon"
private_key_id = "28f0879bf787904cd54da8deb20c4e05623b6019"
private_key= "{{ GCP_JSON_PRIVATE_KEY }}"
client_email = "airflow-connexion@riverflood-lewagon.iam.gserviceaccount.com"
client_id = "117984266685240404291"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/airflow-connexion%40riverflood-lewagon.iam.gserviceaccount.com"
